### ISSUE TITLE
Localization not working

### ISSUE THREAD

**Issue by ohmer1** [OpenVPN/openvpn-gui#216] opened 2018-02-08 18:26 UTC
I configured OpenVPN-GUI to use the french localization in the settings, but the apps is still all in english. I'm using version 11.9.0 (bundled with openvpn 2.4.4) on Windows 10.

**Comment by selvanair** [comment] 2018-02-08 19:12
What do you see if you go back to the settings menu after changing the language? In case of french, you should see group box captions like "User Interface" has changed to "Interface utilisateur" etc. If not, what language shows  up in the "Language:" or "Langue:" box?

Note that messages in the status window will still be in English as openvpn.exe's logs are not localized. Only the GUI dialogs and menus will appear in the chosen language.

**Comment by ohmer1** [comment] 2018-02-08 21:16
If I change it to english and then back in french, the app switch to french.

I said I set the language to french in the settings, but now I think about it, the language was set to french by default (probably because my OS is configured with the french language) but the settings was not applied until I change it manually.

I replicated the issue on two different computers.

**Comment by selvanair** [comment] 2018-02-08 22:23
Its supposed to work without need for manually switching back and forth. In any case what the settings show must match what is used by the rest of the program, so what you see is unexpected. Will try to reproduce.

**Comment by mcornella** [comment] 2019-03-25 11:15
I can confirm. This is a screenshot taken right after installing OpenVPN 2.4.7 (the latest build)
![default lang screenshot](https://user-images.githubusercontent.com/1441704/54914938-69797680-4ef6-11e9-8a1b-14613efffc31.png)

As you can see, the language selected is the right one, but there is no `ui_language` entry under `HKCU\Software\OpenVPN-GUI`, so the UI language doesn't pick the correct value.

After selecting another language and going back to Spanish it does set the `ui_language` entry and the UI shows the correct language:
![spanish lang screenshot](https://user-images.githubusercontent.com/1441704/54915196-e4db2800-4ef6-11e9-8f65-7de58e1f0ff5.png)

It looks like the `HKCU\Software\OpenVPN-GUI` registry path is created on the first start of the GUI program but `ui_language` is not set.

**Comment by mcornella** [comment] 2019-03-25 11:49
This is an easy fix: it should be enough to do the work of `SetGUILanguage` in [`UpdateRegistry`](https://github.com/OpenVPN/openvpn-gui/blob/7bfb9508526adcc1878d679452bd6f268ff4e26b/registry.c#L327), `langId` being equal to the returned value of `GetUserDefaultUILanguage()`:
https://github.com/OpenVPN/openvpn-gui/blob/7bfb9508526adcc1878d679452bd6f268ff4e26b/localization.c#L89-L93

**Comment by selvanair** [comment] 2019-03-25 15:14
Preferences are persisted in the registry only when edited so not  finding ui_language in the registry is not a bug. The GUI is supposed to use the OS default language without needing any registry key. Not persisting default values is by design as that keeps the registry clean and makes it easier to change the defaults in a future versions.

If you are seeing one language in the settings but displays that are inconsistent with that in other menus, there is a bug. I can see that GetRegistryValueNumeric() is used in localization.c without checking the return status. That could set langId to some random value (though unlikely) causing it to fall back to English later in the process. Will try again to reproduce what you see and fix.

**Comment by selvanair** [comment] 2019-03-26 19:57
@mcornella What is your display language set to in the system (Language and Region Settings)?

I think I've managed to reproduce this on Windows 10. The problem is that the default display language returned by GetUserDefualtUILanguage() is different in Windows 10 (possibly 8.1 as well) compared to earlier versions. For, example, with display language set to  Fr-CA, Windows 7 returns 1036 indicating the neutral/primary part of the language (French) which is what we want. But Windows 10 gives 3084 (Fr-CA)  which is more accurate but breaks our resource loading logic.

Still searching for the least painful way to correctly fall back to the closest primary language we have translations for.

**Comment by selvanair** [comment] 2019-03-26 20:54
@ohmer1 @mcornella : please test this version: https://github.com/selvanair/openvpn-gui/releases/tag/sublang

**Comment by mcornella** [comment] 2019-03-26 21:08
> @mcornella What is your display language set to in the system (Language and Region Settings)?

Spanish (Spain) (so `es-ES`).

The version you uploaded works for me.

**Comment by selvanair** [comment] 2019-03-26 21:26
Thanks for testing -- will submit a PR.

Looks like Spanish (sp-ES)  has a traditional vs modern distinction, and sp-ES evaluates as 3082 (0x0C0A)  while its default value is 1032 (0x040A) which only matches traditional Spanish.  https://docs.microsoft.com/en-us/windows/desktop/intl/language-identifier-constants-and-strings

Our resource collection is labelled by the default sublanguage ids. That's why it works when persisted in the registry but not when read from system's default.  Actually, part of the display (like OK, cancel buttons in msg boxes) may show up localized even without the patch  --- only loading our own resources was falling back to English.

Thanks for reporting this bug.

**Comment by mcornella** [comment] 2019-03-26 23:06
Tried with fr-CA and also worked. Good job!

**Comment by selvanair** [comment] 2019-03-29 19:08
Fixed by PR #298. Will be available in next release.

**Closed by selvanair** 2019-03-29 19:08 UTC
