### ISSUE TITLE
OpenVPN fails to reconnect after sleep

### ISSUE THREAD

**Issue by cptully** [OpenVPN/openvpn-gui#311] opened 2019-09-03 17:11 UTC
I have been using OpenVPN on Windows 7 for the last 18 months or so. In the last 3-4 months I have had a problem when waking my computer up from sleep. For example when leaving work for the day I close the lid, stick it in my backpack and go home. I get home, open up my laptop and I now have an error message saying "connection to ... was terminated". When I click the only button on the error dialog, OK, it goes away, as does the usual connection log that was behind it. In this state, sometimes I can still connect to resources on the VPN, and sometimes I cannot. But more importantly, I cannot reconnect to the VPN. I first have to bring up Task Manager and find the openvpn.exe process and kill it manually. Then I can reconnect to the VPN.

OS: Windows 7 Enterprise, Service Pack 1
OpenVPN: 11.13.0.0

**Comment by selvanair** [comment] 2019-09-03 17:43
Sounds like the management interface unexpectedly disconnects on sleep leaving the OpenVPN core process (openvpn.exe) running. I have never seen this.

Could you please post the client log at verb 4? To do this add verb 4 (unless already in there) to the client config file, connect. When the error happens, close the error dialog and open the log file using the "view log" menu.

**Comment by cptully** [comment] 2019-09-03 18:12
@selvanair "verb 1" already existed in my .ovpn file. I changed it to read "verb 4" and replicated my issue. I've attached a copy of my log file since pasting it in always concatenated the text into one long line in the preview.

[verb_4_logfile.txt](https://github.com/OpenVPN/openvpn-gui/files/3570851/verb_4_logfile.txt)

**Comment by selvanair** [comment] 2019-09-03 19:11
The logs shows it reconnected without error after the sleep/resume event:

`Tue Sep 03 14:02:06 2019 us=553119 SIGHUP[soft,tun-abort] received, process restarting `
This is triggered by the tun adapter reset on sleep
`Tue Sep 03 14:02:38 2019 us=575004 Attempting to establish TCP connection with [AF_INET]40.121.220.134:1194 [nonblock]`
Showing the reconnection attempt after resume, and finally
`Tue Sep 03 14:02:50 2019 us=574690 MANAGEMENT: STATE:1567533770,CONNECTED,SUCCESS,10.22.15.232,40.121.220.134,1194,192.168.111.10,26507`
showing successful reconnect.

Except that you seem to be running the GUI as admin (run-as-admin?), which is not recommended, and it takes about 12 seconds for the reconnect sequence to complete (slow network?), I see nothing wrong in here.

Curiously, it opens "OpenVPN Tap 1" adapter in the first round, but fails to open it on reconnect, and instead uses "OpenVPN Tap 2". This could happen if you have multiple tunnels running, as those may restart in a random order on resume. Otherwise this is unusual.

Please run the GUI (and thus OpenVPN) without elevation (as user). This requires the interactive service to be running which is installed and started by default.

**Comment by cptully** [comment] 2019-09-04 13:24
1) As a developer my user is currently a member of the administrators group
on this computer. So, when I installed OpenVPN, I installed it as an Admin
and the file propertioes on openvpn-gui.exe show that it is owned by the
Administrators group.
2) It was automatically configured to start with Windows, so I am not
manually running it. And on the rare occasion that I do manually run it, I
do not choose the "Run as Administrator" option.
3) I have three Tap Windows adapters installed, because I often have to
connect to two and sometimes three different VPNS at the same time.

So, how do I start it with non admin privileges in that environment?

Chris Tully
cptully@gmail.com
240-475-9753 (c)

[image: View my profile on LinkedIn]
<http://www.linkedin.com/in/christully/>                *Check me out on*
<https://github.com/cptully>

**Comment by selvanair** [comment] 2019-09-04 15:12
As you posted this as an issue here (the GUI repo), I assumed you are using OpenVPN-GUI. Also the log file you posted was using the GUI run as admin.

If the issue is when  automatically started on boot using OpenVPNService, I do not understand what you mean by the dialog that shows up as connection terminated. There is no desktop interaction when started on boot and there wont be any dialog alerting connection errors.

Anyway, if autostarted, post logs showing connection error. The last log file you attached was for running from the GUI and showed nothing wrong.

If there are no errors in the logs and openvpn.exe is still running but no traffic flows, you may be losing routes or the tunnel IP after sleep -- hard to say without further info on exactly what the problem is. Note the way to restart misbehaving autostarted connections would be to start and stop the service.
```
sc stop OpenVPNService
sc start OpenVPNService
```

Trying to manually run from the command prompt or the GUI when the same connection is being autostarted on boot will cause conflicts and error.

In fact autostarting on boot causes all connections (.ovpn's) in C:\Program Files\OpenVPN\config\ to be started on boot. Move configs that should be manually controlled (started/stopped by user from cmd prompt or using the GUI) to %USERPROFILE%\OpenVPN\config or its subfolders.

> And on the rare occasion that I do manually run it, I do not choose the "Run as Administrator" option.

When starting manually from the command prompt (not using the GUI) you need to start it as administrator (from an elevated command prompt, for example). Else adding routes will fail. Also
currently there is no way of running with limited privileges when started on boot -- the automatic service runs as SYSTEM and so does openvpn. I was referring to starting from the GUI.

> As a developer my user is currently a member of the administrators group on this computer. So, when I installed OpenVPN, I installed it as an Admin and the file propertioes on openvpn-gui.exe show that it is owned by the Administrators group.

That is fine. Yet, if using the GUI, just double click on its icon to start it  -- that is, do not run-as-admin (elevated) or do not set the GUI short-cut to run-as-admin. Saying this again as the log file showed otherwise.

**Comment by cptully** [comment] 2019-09-04 15:28
Thank you for the detailed response!

None of my .ovpn files are in the  C:\Program Files\OpenVPN\config\
directory. They are all stored under C:\Users\tullych\OpenVPN\config for
ease of access and ease of editing (Yes, I have had to edit the files more
than once). I always manually start my tunnels using the OpenVPN GUI. When
I quit the OpenVPN GUI for some reason, I always restart it by going to my
start menu, finding OpenVPN GUI and clicking on it. No run as administrator.

When I am connected to a tunnel, I see three OpenVPN processes in my task
manager:
[image: image.png]

When I run into the issue that I initially posted about, I see one instance
of openvpn.exe per tunnel I was connected to before sleeping the computer.
By experimentation, I have found that I can manually kill the instances of
openvpn.exe and then I am able to reconnect to the tunnels at will.
Next time I will try restarting the OpenVPNService.

Chris

Chris Tully
cptully@gmail.com
240-475-9753 (c)

[image: View my profile on LinkedIn]
<http://www.linkedin.com/in/christully/>                *Check me out on*
<https://github.com/cptully>

**Comment by selvanair** [comment] 2019-09-04 15:48
> Next time I will try restarting the OpenVPNService.

Oh, no...

You are using the GUI and connections are started after a user logs in, so you can ignore everything about "autostrated on boot" that I wrote. Do not start or stop OpenVPNService (its disabled by default) -- I mentioned it only because you said connections are started at boot which is not the case.

Anyway, somehow your GUI is running as root. Check the properties of the GUI short-cut. It could be set to run as admin by some one. Else it will not run as admin as your logs showed.

If the GUI reports connection terminated abnormally but corresponding  openvpn.exe is still running, you will have to kill it manually to get back to normal. But this should not happen. If it does, post logs from such an occurrence. Before that get the GUI to run with limited privileges.

**Comment by cptully** [comment] 2019-09-04 15:59
I just check Properties on the OpenVPN GUI shortcut on my start menu and In
the Advanced dialog, Run as Administrator is unchecked.

How would I check the privileges used when OpenVPN GUI is run at startup?

Chris


Chris Tully
cptully@gmail.com
240-475-9753 (c)

[image: View my profile on LinkedIn]
<http://www.linkedin.com/in/christully/>                *Check me out on*
<https://github.com/cptully>

**Comment by selvanair** [comment] 2019-09-04 16:22
To show the elevation/UAC virtualizations status of processes in task manager, use the "view->Select Columns" dialog and select "UAC virtualization". The column will state "disabled" for processes running with limited privileges.

It could be that you have UAC disabled on your Windows 7 machine? If so either you know what you are doing (meaning you can somehow arrange to start the GUI with limited privileges) or you should be enabling UAC which is the default.

That said, the problem you face should not happen even if the GUI is run as admin. However, that usage is highly discouraged and many recent changes may not be well tested for the code-path followed when run as admin. As far as I'm concerned running the GUI  as admin is an unsupported use case in 2.4 release. Hence the request to not do that.

**Comment by cptully** [comment] 2019-09-04 18:46
Looking at Process Explorer (by Sysinternals), openvpn.exe and
openvpn-gui.exe are both run by my user, oenvpnserv.exe is run by NT
AUTHORITY\SYSTEM.

UAC was disabled by IT when they configured the computer, but I have put it
back to default settings.

Chris


Chris Tully
cptully@gmail.com
240-475-9753 (c)

[image: View my profile on LinkedIn]
<http://www.linkedin.com/in/christully/>                *Check me out on*
<https://github.com/cptully>

**Comment by selvanair** [comment] 2019-09-04 19:07
On Windows a process may run as a user but still could be either elevated or not depending on its UAC status which could be checked from task manager or process explorer. On process explorer double click the process to open the properties window,  go to  security tab and check whether Administrators group flag shows Deny or Allow. On Task manager follow what I wrote before. 

Anyway, quit the GUI and start again after UAC is enabled and see what happens on sleep/resume. If it still shows a disconnect error with openvpn.exe left running, please post the logs.

**Comment by yanivps** [comment] 2020-06-17 05:31
For me what works is disable the network adapter (TAP-Windows Adapter V9 for OpenVPN Connect) and renable it, OpenVPN Connect reconnect automatically and things are back normal
But I still have to admit this issue is kind of annoying and a fix for this problem would be great

**Comment by selvanair** [comment] 2020-06-17 13:59
The original report had a mistaken use of OpenVPNService and  probably was user error as there was no follow up.

Anyway, VPN should automatically resume after waking from sleep, that's what happens with me.  If that's not the case, open a new issue with detailed logs and version info.

**Comment by xiic** [comment] 2020-07-07 08:49
Having the same issue since a few days/weeks or so.
OS: Windows 10 1909

After the PC goes to sleep mode and wakes up again, the VPN is not working any more. It is still connected, a few Bytes are going out and coming in (according to the GUI), but nothing is transferred. Disconnect and Reconnect doesn't help.

If I disable the TAP adapter and enable it, everything is working again (until the computer goes to sleep mode again).

**Closed** 2020-07-07 15:11 UTC

**Comment by cptully** [comment] 2020-07-07 17:55
I stopped following this thread because I have left the company where I was using openVPN. For what it's worth none of the suggestions above solved my issue. Perhaps the new computer that I was slated to get shortly after I left would have solved the issue but as I am no longer working there, I do not know. I am fine with leaving this in closed state, only because I am no longer using openVPN, so I cannot test further...
