### ISSUE TITLE
Only 50 configurations allowed - need unlimited!

### ISSUE THREAD

**Issue by user18x** [OpenVPN/openvpn-gui#235] opened 2018-03-25 10:40 UTC
Hello,

i use openvpn 2.4.4 (now openvpn 2.4.5) but only 50 configurations allowed, i need more!
Can it be "fixed" to unlimited in a newer version?

I've more than 50 config files in the openvpn config-folder.
So if i click on openvpn-icon (gui; graphical user intercae) in tray a message "pops up" with only 50 configurations allowed (sorry the message is in german). 
![nur 50 konfigurationen](https://user-images.githubusercontent.com/37771000/37874149-a1f90134-3029-11e8-901a-a26c2c52d2ad.jpg)

**Comment by user18x** [comment] 2018-04-04 16:21
Hmm, will it be fixed?

**Comment by mattock** [comment] 2018-04-09 09:59
@user18x can try with 49 configurations? Does the UI work ok with that many? Can you provide a screenshot?

**Comment by user18x** [comment] 2018-04-09 17:10
49 configs and less does work!
But i need more than 50!

**Comment by chipitsine** [comment] 2018-04-10 07:12
@mattock , @selvanair - what if we change default with 250 ?
UI wouldn't be worse

**Comment by user18x** [comment] 2018-04-10 08:36
Why a limit?
If it needs a limit, then 250 sounds good.

**Comment by chipitsine** [comment] 2018-04-10 09:30
@user18x - historically, there's limit. please look at the code, it is written such way.
if you are not happy with that limitation, you can always send PR (or hire a developer)
if that PR is good, it will be merged and limitation will go away

**Comment by selvanair** [comment] 2018-04-10 13:53
Technically, in the current design one can push to about ~6000 configs. But, IMO, anything more than a few dozen will be hard to use with popup menus, and a list view is better and more versatile for such large lists. But such a change is some work and unlikely to happen unless someone sends in a patch.

I suggest we build the release binaries with MAX_CONFIGS = 1000. It wont affect the look, feel or performance[*] for most users who have a few configs. And those with 100's can still have their fun.

There is also a max sub-directories limit of 50 but that can be lifted by changing the way config files are scanned for -- easy to fix.

[*] Except for a couple of MB wasted memory (bss) which can be avoided with some code changes but not worth the effort? The data size doesn't change so the executable will remain the same size.

**Comment by chipitsine** [comment] 2018-04-11 07:33
I recall some old thread with enabling mouse wheel on config list.
I tried on my test 49 configs, mouse wheel is not working.

can we enable it as well ? (I'll do some investigation myself on that)

**Comment by selvanair** [comment] 2018-04-14 18:47
I did some tests with a few hundred configs. The UI becomes very hard to use (one has to scroll all the way down to even exit out). If we do this, the users are going to complain about poor design.

So, below is a screenshot of an alternative that I could quickly put together: a hierarchical menu with configs in each subdirectory grouped into one. 

![grouped-configs](https://ibin.co/3yNqhWoqGiQW.png)

To not surprise current users, the view switches to this form only if the number of configs is > 50. It will be useful only when configs are organized into subdirectories with multiple configs in each. There is no support for re-arranging configs or for changing their group name from within the UI. Up to about 25 configs per subdirectories look easy to use, though the code imposes no limits. Except for a technical limit of a max 65K menu items and performance is not optimized to handle anything beyond ~1000 configs.

**Comment by cron2** [comment] 2018-04-14 18:54
Hi,

On Sat, Apr 14, 2018 at 06:47:06PM +0000, Selva Nair wrote:
> I did some tests with a few hundred configs. The UI becomes very hard to use (one has to scroll all the way down to even exit out). If we do this, the users are going to complain about poor design.
> 
> So, below is a screenshot of an alternative that I could quickly put together: a hierarchical menu with configs in each subdirectory grouped into one. 
> 
> ![grouped-configs](https://ibin.co/3yNqhWoqGiQW.png)

Makes sense to me.  Feature-ACK :-)

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by chipitsine** [comment] 2018-04-15 06:14
What if we will add optional icon on the left of config name? It would simplify navigation

@selvanair ?

**Comment by selvanair** [comment] 2018-04-15 16:00
Icons for each config would be a nice addition. LBut I'm restricting this proposal to just removing arbitrary limits on number of configs and having a reasonable way of listing a large number of them.

As for improving UX, especially with more than a handful of configs, we'll need further changes. I'll most a test exe for user feedback.

**Comment by selvanair** [comment] 2018-04-15 16:01
oops..

**Comment by mattock** [comment] 2018-04-16 07:50
The new layout looks good. Just one question: what if we show the configs that are in the main config directory in the main menus, and the configs in directories inside submenus? Most people would probably notice no difference as I assume they have configs in the main directory. And those few who have 50+ configs could be told (in the error/warning message) to organize their configs into subdirectories.

This way people with less than 50 configs could still benefit from the ability to group VPN configs, e.g.

* CUSTOMERS
  * customer_a
  * customer_b
* VPN_PROVIDERS
  * provider_a
  * provider_b
* config_on_main_level
* another_config_on_main_level

**Comment by cron2** [comment] 2018-04-16 08:07
Hi,

On Mon, Apr 16, 2018 at 07:50:29AM +0000, Samuli Seppänen wrote:
> * CUSTOMERS
>   * customer_a
>   * customer_b
> * VPN_PROVIDERS
>   * provider_a
>   * provider_b
> * config_on_main_level
> * another_config_on_main_level

This is what my mental "deployment model" assumed it would look like :-)

So, yes!

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by selvanair** [comment] 2018-04-16 12:00
@mattock:
Yes, that is the plan -- configs in main directory are shown in the main menu. As for those with less than 50 configs, we can have an option to enforce the new view regardless of number of configs.

**Comment by selvanair** [comment] 2018-04-17 21:02
Please test this draft version:
https://github.com/selvanair/openvpn-gui/releases/tag/max-config-v3

**Comment by selvanair** [comment] 2018-05-04 16:31
You can add configs to user profile (C:\Users\username\OpenVPN\config\...) or to the global location "C:\Program Files\OpenVPN\config\..". These and their subdirectories are scanned up to a depth of four. In the menu, all configs in the latter location will show up with an additional level of nesting under an item named "System Profiles".

Menus as such do not support scrolling. Though it may be possible to hack up something,  a proper solution would need to use a different UI to list the configs instead of the current popup menu. That's a major overhaul.

**Comment by user18x** [comment] 2018-05-11 09:31
Is it final now?

**Comment by user18x** [comment] 2018-05-29 08:44
Will it be in the next openvpn-setup.exe?

**Comment by hesss5** [comment] 2018-07-02 22:51
Nested listing of connnection profiles is excellent please add it soon
thanks

**Comment by xp65** [comment] 2018-10-02 11:58
It's a feature we would like as well, nested + higher (or unlimited) limit.

**Comment by selvanair** [comment] 2018-10-02 14:58
This is implemented in PR #247 -- you can help by testing it and reporting back. For a test executable, see https://github.com/selvanair/openvpn-gui/releases/tag/max-config-v3

Or use the exe in appveyor artifacts of the PR 
https://ci.appveyor.com/project/mattock/openvpn-gui/build/cygwin-185/job/ptouunmhacb7ltii/artifacts

The latter will disappear after 6 months which is in a few days!

**Comment by SmoochySix4** [comment] 2018-10-03 23:50
Why not add sub-directory support to the current pop-up menu? Is this possible?

**Comment by hesss5** [comment] 2018-10-04 00:03
32 bit please

**Comment by selvanair** [comment] 2018-10-04 02:29
@SmoochySix4 
> Why not add sub-directory support to the current pop-up menu? Is this possible?

Not sure what you mean -- subdirectories (up to one level deep under the config directory) is already supported. What this patch does is to make the menu also nested and scan subdirectories up to four levels deep.

**Comment by webluke** [comment] 2018-11-05 20:51
Testing in my user config folder, this was exactly what I was looking for. I used folders to organize based on region of a set of 52 servers from a subscription VPN service. I even have one that is in 2 folders deep and it works great. 

![image](https://user-images.githubusercontent.com/5162188/48025697-64f82100-e101-11e8-8269-fb3732af43ea.png)

The only problem I still have is when you have a long list you can't use the scroll wheel on the mouse to move through a list, you must go to the arrow and click at the top or bottom. Also the empty space on the left of the name seems like you should be able to configure an icon there or just remove it, it's probably just something built into the windows menu you can't remove.

**Comment by selvanair** [comment] 2018-11-05 21:20
Context menu UI by design does not capture the mouse wheel so that's not going to happen -- unless someone submits a patch that uses a different UI element (like a list view). 

The space on the left is currently used for adding a tick when connected. It can take an icon -- patches welcome.

**Comment by MSMWForrest** [comment] 2018-11-22 18:20
This solution is (almost) perfect for us!

We have several hundred buildings that we remotely connect to, and sorting them in sub-folders by first letter makes them much easier to work with, but unfortunately the client at https://github.com/selvanair/openvpn-gui/releases/tag/max-config-v3 crashes on my machine.

It works fine for my co-workers, and I can also get it to work if I start the client with 49 or less configs, then add the remaining configs.

Adding "--config_menu_view 1" or  "--config_menu_view 2" makes no difference. If I have 49 or less configs on startup, it works, 50 or more, it crashes, and both options work if I start with 49 or less configs then add the remaining configs after.

I've re-installed OpenVPN, tried moving the configs to different directories, and so forth. I've also run "Procmon.exe" and basically it seems to crash right after successfully reading all the configs.

**Comment by selvanair** [comment] 2018-11-27 22:41
@MSMWForrest I looked into the error you reported. It took while to debug this and there indeed is a subtle error that could cause random crashes. Pointers to potentially reallocated memory is used as a data structure member which is obviously a no-no. Everything works as long as realloc does not move the memory but fails otherwise.

I have uploaded a new binary to the [pre-release]( https://github.com/selvanair/openvpn-gui/releases/tag/max-config-v3) Hope it works. The source code for it is  in this [branch](https://github.com/selvanair/openvpn-gui/tree/max-configs-v5) which is same as the PR plus two fixup commits. Also the automatic switching of config menu view now happens at 25 configs.

**Comment by MSMWForrest** [comment] 2018-11-27 23:05
@selvanair It works!

It's not crashing on my machine anymore. I'll spread the word here with my co-workers, and see if anybody else runs into any issues.

Thanks a ton for all your work on this!

**Comment by selvanair** [comment] 2018-11-28 02:38
I've updated PR #247 and also the[ test-release binaries](https://github.com/selvanair/openvpn-gui/releases/tag/max-config-v3) to match it as there were a few finer details left out in the test version of earlier today.

**Comment by selvanair** [comment] 2019-01-21 16:39
Thanks for testing.

Looks like you have found a bug in a previous commit which we merged recently (PR: https://github.com/OpenVPN/openvpn-gui/pull/282). That one introduced ignoring pushed --route-method using pull-filter on command line which trips the authorization check in interactive service. Will fix. 

For testing I'll post a new executable that does not include the offending commit.

**Comment by Ibeme85** [comment] 2019-01-21 16:43
Great to hear.

I'm waiting for the new executable to test it again. :)

**Comment by cron2** [comment] 2019-01-21 16:53
hi,

On Mon, Jan 21, 2019 at 04:39:20PM +0000, Selva Nair wrote:
> Looks like you have found a bug in a previous commit which we merged recently (PR: https://github.com/OpenVPN/openvpn-gui/pull/282). That one introduced ignoring pushed --route-method using pull-filter on command line which trips the authorization check in interactive service. Will fix. 

Oops :-)

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by selvanair** [comment] 2019-01-21 17:08
Fixing my own errors:

I suggest we white-list `--pull-filter` as user specifiable option in interactive service. Looks safe to me as that only overrides the sever, not locally set options. The current list of white-listed options are (from src/openvpnserv/validate.c).

```
static const WCHAR *white_list[] =
{
    L"auth-retry",
    L"config",
    L"log",
    L"log-append",
    L"management",
    L"management-forget-disconnect",
    L"management-hold",
    L"management-query-passwords",
    L"management-query-proxy",
    L"management-signal",
    L"management-up-down",
    L"mute",
    L"setenv",
    L"service",
    L"verb",

    NULL                                /* last value */
};
```

 While at it we could also add --script-security required for PR #271. Any caveats?

**Comment by selvanair** [comment] 2019-01-21 17:39
@Ibeme85 The draft release is updated with a new exe. Please test.

https://github.com/selvanair/openvpn-gui/releases/tag/max-configs-v6

The only difference is that the offending commit is reverted.

**Comment by selvanair** [comment] 2019-02-20 19:03
Feature implemented in PR 247 (merged). Closing.

**Closed by selvanair** 2019-02-20 19:03 UTC
