### ISSUE TITLE
OpenVPN-2.6.0-I003-amd64: Error creating semaphore

### ISSUE THREAD

**Issue by Gulaschcowboy** [OpenVPN/openvpn-gui#598] opened 2023-02-02 10:43 UTC
Yesterday we pushed OpenVPN-2.6.0-I003-amd64 to our Dell Laptops with Windows 10, various builds.

On some of them an error message pops up during start of the OpenVPN-Gui.
"Error creating semaphore":

![grafik](https://user-images.githubusercontent.com/17720393/216303081-48213c87-3934-4175-a120-66a438481095.png)

It doesn't seem to have an impact, and we couldn't figure out yet, why some Laptops are affected and some not.

Downgrading to 2.5.8 doesn't help, the error persists after downgrade.

Any hints?

**Comment by lstipakov** [comment] 2023-02-02 14:15
Anything interesting in Windows Event Log?

**Comment by Gulaschcowboy** [comment] 2023-02-02 14:59
Hi, we see this:
![grafik](https://user-images.githubusercontent.com/17720393/216359623-441e9e82-d368-40cd-a398-50bef5e9f22e.png)

**Comment by selvanair** [comment] 2023-02-02 15:17
That error looks like its from the installer which sets to restart the GUI if it was running during upgrade. I do not know why that happens. Looks like the GUI was running with some privileges that the installer could not revert to. Are you running the GUI with admin privileges (using run-as, for example?) -- if yes, do not do that.

As for the semaphore, it is used to avoid multiple instances and detect a running instance to which commands can be sent. An error here is not fatal, but unexpected.
One reason it can fail is when another object (not a semaphore) with the same name ("Local\\OpenVPN GUI") exists --- like an event, mutex etc. which all share the same namespace. But that's unlikely. Unfortunately we do not log the error number for this.

Can you try to create a semaphore with same name from powershell and see you get any error:
`$sem = New-Object System.Threading.Semaphore(1, 1, "OpenVPN GUI")`  
(leave out the "Local\" prefix).
If that succeeds, try to acquire it as
`$sem.WaitOne(0)`
That should return false if the GUI is running and has locked the sempahore. Else it will return true. Finally release it with
`$sem.Release()`

**Comment by Gulaschcowboy** [comment] 2023-02-02 16:23
"Are you running the GUI with admin privileges (using run-as, for example?) -- if yes, do not do that." - no we are certainly not doing that.
At the moment we have the issue that we had to return the laptops  to the users, so getting hand on an affected device is not that easy.
We'll try the above steps as soon as possible. And thanks for the explanation.

**Comment by Gulaschcowboy** [comment] 2023-02-03 06:48
Hi @selvanair did as you requested:
PS C:\Users\Alex> $sem = New-Object System.Threading.Semaphore(1, 1, "OpenVPN GUI")
PS C:\Users\Alex> $sem.WaitOne(0)
False
PS C:\Users\Alex> $sem.Release()
0
But above is an artifical test, as this machine wasn't affected in the first place.

Also it seems that the error disappeared from all affected users, probabply after they rebooted.
Maybe worth to mention here: The initial upgrade to 2.6 was pushed out by Manage Engine when this error occured.
Because of another issue with the dco driver and we reverted manually and then the error persisted.

Overall it could be an edge case with no serious effect, that I can't efficiently repriduce now, as we had to rollback to 2.5.8 because of dco.

**Comment by selvanair** [comment] 2023-02-03 17:16
Thanks for the feedback.

> PS C:\Users\Alex> $sem.WaitOne(0)
> False

Yes, this is the expected behaviour when the GUI is holding the semaphore.

Anyway, as affected machines are cured by rebooting, I'll close this. You may want to report the dco issue to [OpenVPN/dco-win ](https://github.com/OpenVPN/ovpn-dco-win/issues) or [OpenVPN/openvpn](https://github.com/OpenVPN/openvpn/issues)

**Closed** 2023-02-03 18:44 UTC
