### ISSUE TITLE
Option to disable 'save password'

### ISSUE THREAD

**Issue by wimg** [OpenVPN/openvpn-gui#105] opened 2016-12-08 11:49 UTC
For ISO27001 certification, we are not allowed to let users save their VPN passwords locally. Is there a way to remove or disable the 'save password' box upon authentication ?

**Comment by selvanair** [comment] 2016-12-08 17:32
There is no option to do this but could be achieved using an up-script [1]. Note that passwords are saved in an encrypted form using CryptProtectData and can be decrypted only by the same user. The OpenVPN core (openvpn.exe) also saves the password unless explicitly disabled using --auth-nocache.

[1] When a connection is up, the GUI runs the script named "configname_up.bat", if found in the same folder as the config file. You could have the script do

reg delete HKCU\Software\OpenVPN-GUI\configs\configname  /v auth-data /f
reg delete HKCU\Software\OpenVPN-GUI\configs\configname  /v key-data /f
exit 0 # ignore any value not found error

That will delete the stored passwords for the key and auth-user-pass, if any. Here configname is the basename of the config file (i.e., if the config file is  "myvpn.ovpn", configname would be "myvpn", and the up-script be named "myvpn_up.bat"

**Comment by chipitsine** [comment] 2016-12-08 18:20
passwords are actually stored using DPAPI (data protection api), it is not possible to steal those passwords. what is ISO 27001 requirement exactly ?

as for pure disabling, we might implement separate configure option and you (or someone) can build custom installer

**Comment by selvanair** [comment] 2016-12-08 18:55
As @chipitsine wrote, I'm also curious about the exact wording of the ISO 27001 requirement. I've heard they have requirements like not allowing access to source code etc. which makes little sense.

Anyway, here is a better alternative to my proposal to use GUI up-script: Use an openvpn up-script instead. This is better as it runs even during reconnections, and need not be batch files. To do this use a script or executable that deletes the registry keys listed in my previous reply (do not name the script as configname_up.bat to avoid the GUI running it, though that cant hurt). Then to the connection config file add

script-security 2 # needed to run user-defined scripts
up scriptname  # replace script name with path relative to the config folder or full path
auth-nocache  # openvpn will prompt passwords even for reconnections

Building with the option disabled is not very useful as a user can always install another version of the GUI and save passwords.

**Comment by wimg** [comment] 2016-12-08 19:57
I'm not aware of the exact text of the ISO certification, it's for one of our customers.

The problem is that the VPN is started by a non-admin, so using an up script apparently doesn't work there :-(

**Comment by selvanair** [comment] 2016-12-08 20:13
>The problem is that the VPN is started by a non-admin, so using an up script apparently doesn't work there :-(

That's exactly why the script would work. The script has to execute as user, as the saved password is in user's HKCU. Even if the same config is shared by many users, the script will delete the appropriate key for the user executing it. 

That said it will only satisfy the spirit if the requirement, the save-password checkbox will still appear in the dialogs though their effect is internally invalidated by the script. May not be enough to pass a superficial audit..

**Comment by selvanair** [comment] 2016-12-11 18:41
A test version that disables the save-password feature if --auth-nocache is in the config is [here](https://github.com/selvanair/openvpn-gui/releases/tag/v11-auth-nocache). The  [GUI executable](https://github.com/selvanair/openvpn-gui/releases/download/v11-auth-nocache/openvpn-gui-nocache.exe) is 64 bit only -- sources are [in this feature branch](https://github.com/selvanair/openvpn-gui/commits/no-savepass).

It involves adding a config file parser, so too complex to make into the upcoming 2.4 release. Will have to wait for 2.4.1 at least.

**Comment by Deantwo** [comment] 2017-01-09 07:50
I am in the same boat as @wimg with a ISO certification around the corner. But don't know the all the specifics of the requirements myself yet.

As a whole my boss isn't much for the idea that customers can save their passwords even if it isn't/wasn't a requirement of ISO.

Why would you want to bind this functionality to `--auth-nocache` anyway? Seems a little odd.
A much more logical way to do it, would be to use the method already mentioned in the OpenVPN documentation. If the file defined in `--auth-user-pass "file.txt"` only contains one line, only prompt for password and don't allow it to be saved.

This is discussed in this forum thread: https://forums.openvpn.net/viewtopic.php?t=11728

And see: [`--auth-user-pass [up]` in the manual](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage)

**Comment by chipitsine** [comment] 2017-01-09 07:56
we may actually compile openvpn-gui.exe without such option. and ship 2 separate openvpn-gui.exe in installer.

it seems to be complicated, however, it will stop people from rolling custom installers and gain more users to openvpn itself

@selvanair  ?

**Comment by chipitsine** [comment] 2017-01-09 08:13
another option would be to use modern challenge-response mech (instead of regular user/password), as far as I know, CR is not saved ?

**Comment by selvanair** [comment] 2017-01-09 15:48
> Why would you want to bind this functionality to --auth-nocache anyway? Seems a little odd.
> A much more logical way to do it, would be to use the method already mentioned in the OpenVPN documentation. If the file defined in --auth-user-pass "file.txt" only contains one line, only prompt for password and don't allow it to be saved.

In the current implementation there is no way to take the username from file and password from the GUI and I see no reason to implement it as usernames could be safely saved in the GUI. (Username from file and password from console is possible while running openvpn from the command line). 

In any case what you suggest boils down to "not saving the password" and that is unrelated to how username is obtained.

The reason for linking auth-nocache with saving passwords is that If you do not use --auth-nocache openvpn will cache the password in memory. Those who do not want passwords saved may also do not want it cached by openvpn.. But I see that an independent admin-only option to disable password save would be useful.

**Comment by selvanair** [comment] 2017-01-13 23:08
A test executable for disable password save as in PR #117 may be found [here](https://github.com/selvanair/openvpn-gui/releases/tag/v11.4.0.3)

Test reports and/or review of the code in PR #117 most welcome.

**Comment by appunnicer13** [comment] 2017-01-23 05:54
I use openVPN GUI in my windows 10 computer. There is a problem with it, I am trying to use multiple HTTP proxies using connection tags , our connections are limited by TCP 80 , 443 ports so I used same remote host for all my connections , then i had 5 -6 http proxiess through which i wanted the OPENVPN to iterate, but the problem is that it is not iterating the credentials as well while  iterating the connection . HTTP proxy Credentials are somehow cached and not iterated through.  . I believe that this is not an intended behaviour and caused while trying to Cache Credentials of the openvpn-gui .  

https://drive.google.com/file/d/0BwlvQ0O2HFzzVUVZYjZSQ05FY3pnb0U0VUNrUUpLTnN5bG1J/view?usp=sharing  here is the typical config.

**Comment by chipitsine** [comment] 2017-01-23 06:18
your config file seem to be generated by OpenVPN Access Server, right ?
if so, it is separate product, not based on openvpn-gui

**Comment by Deantwo** [comment] 2017-01-23 06:49
Even if it is a openvpn-gui problem, it should be posted as a separate issu. It doesn't make sense as a comment under an existing and unrrlated issue.

Try this: https://github.com/OpenVPN/openvpn-gui/issues/new

**Comment by selvanair** [comment] 2017-05-12 15:04
Resolved by commit 778cc3d225819b5e5be938eeaba9493438e1f7d9

**Closed by selvanair** 2017-05-12 15:04 UTC

**Comment by regs01** [comment] 2017-05-17 22:57
@chipitsine so you can't just copy registry keys to another PC?
