### ISSUE TITLE
save password does not work

### ISSUE THREAD

**Issue by illumilore** [OpenVPN/openvpn-gui#161] opened 2017-05-01 05:20 UTC
After entering in a login and password, openvpn will say it is connected, but after a time, if the connection fails, openvpn gui will not auto-reconnect and instead I will be presented with the same window asking for login credentials, with the old login username field still filled out but the password blank, meaning it did not save.

**Comment by selvanair** [comment] 2017-05-01 14:24
I suppose you are using the GUI bundled with 2.4.x distribution. Does the password dialog show the "save password" checkbox? If the checkbox is missing saving of passwords is disabled -- check the registry key HKLM\Software\OpenVPN\disable_save_passwords.

**Comment by illumilore** [comment] 2017-05-01 21:03
The checkbox is present and checked. The gui version is 11.5.0.0.
This seems to happen after a time, like after a few days of being connected.

**Comment by selvanair** [comment] 2017-05-01 21:36
The only time password is deleted is when the user unchecks the save-password box or when the server returns user authentication failure. Taht latter would normally happen only if the username/password is wrong. In that case the client log will show "... MANAGEMENT >STATE:xxxx,RECONNECTING,auth-failure..." 

Please post a snippet of the client log that shows the restart reason when this happens: like SIGUSR1[soft,tls-error] etc. followed by a RECONENCTING,xxx line.  If its a loss of connectivity, the log would have RECONNECTING,tls-error,.... or RECONNECTING,ping-restart,... and password will not be erased. What we are looking for reconnection reason stated as auth-failure.

**Comment by illumilore** [comment] 2017-05-02 03:53
Fri Apr 28 20:00:19 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #33990968 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 28 20:00:19 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #33990969 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 28 20:00:19 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #33990973 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 28 20:03:20 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #34178905 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 28 20:03:20 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #34178906 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 28 20:03:20 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #34178908 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 28 20:03:20 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #34178909 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 28 20:03:20 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #34178910 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 28 20:03:20 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #34178916 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Fri Apr 28 20:04:13 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #34235969 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sat Apr 29 23:24:07 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #39181202 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sat Apr 29 23:24:07 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #39181203 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sat Apr 29 23:24:07 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #39181205 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sat Apr 29 23:24:07 2017 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #39181206 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sun Apr 30 05:02:01 2017 [4e6f0e412dafba4add2d6178916260a5] Inactivity timeout (--ping-restart), restarting
Sun Apr 30 05:02:02 2017 SIGUSR1[soft,ping-restart] received, process restarting
Sun Apr 30 05:02:07 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.4:1198
Sun Apr 30 05:02:07 2017 UDP link local: (not bound)
Sun Apr 30 05:02:07 2017 UDP link remote: [AF_INET]172.98.67.4:1198
Sun Apr 30 05:02:07 2017 [4e6f0e412dafba4add2d6178916260a5] Peer Connection Initiated with [AF_INET]172.98.67.4:1198
Sun Apr 30 05:02:14 2017 AUTH: Received control message: AUTH_FAILED
Sun Apr 30 05:02:14 2017 SIGUSR1[soft,auth-failure] received, process restarting
Sun Apr 30 23:11:58 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.4:1198
Sun Apr 30 23:11:58 2017 UDP link local: (not bound)
Sun Apr 30 23:11:58 2017 UDP link remote: [AF_INET]172.98.67.4:1198
Sun Apr 30 23:11:58 2017 [4e6f0e412dafba4add2d6178916260a5] Peer Connection Initiated with [AF_INET]172.98.67.4:1198
Sun Apr 30 23:12:04 2017 AUTH: Received control message: AUTH_FAILED
Sun Apr 30 23:12:04 2017 SIGUSR1[soft,auth-failure] received, process restarting
Sun Apr 30 23:12:15 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.4:1198
Sun Apr 30 23:12:15 2017 UDP link local: (not bound)
Sun Apr 30 23:12:15 2017 UDP link remote: [AF_INET]172.98.67.4:1198
Sun Apr 30 23:12:16 2017 [4e6f0e412dafba4add2d6178916260a5] Peer Connection Initiated with [AF_INET]172.98.67.4:1198
Sun Apr 30 23:12:17 2017 AUTH: Received control message: AUTH_FAILED
Sun Apr 30 23:12:17 2017 SIGUSR1[soft,auth-failure] received, process restarting
Sun Apr 30 23:12:34 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.4:1198
Sun Apr 30 23:12:34 2017 UDP link local: (not bound)
Sun Apr 30 23:12:34 2017 UDP link remote: [AF_INET]172.98.67.4:1198
Sun Apr 30 23:12:34 2017 [4e6f0e412dafba4add2d6178916260a5] Peer Connection Initiated with [AF_INET]172.98.67.4:1198
Sun Apr 30 23:12:35 2017 Preserving previous TUN/TAP instance: pia virtual
Sun Apr 30 23:12:35 2017 NOTE: Pulled options changed on restart, will need to close and reopen TUN/TAP device.
Sun Apr 30 23:12:36 2017 open_tun
Sun Apr 30 23:12:36 2017 TAP-WIN32 device [pia virtual] opened: \\.\Global\{4E56AD95-0ECF-412C-9467-C01FDA916F99}.tap
Sun Apr 30 23:12:36 2017 Notified TAP-Windows driver to set a DHCP IP/netmask of 10.74.10.6/255.255.255.252 on interface {4E56AD95-0ECF-412C-9467-C01FDA916F99} [DHCP-serv: 10.74.10.5, lease-time: 31536000]
Sun Apr 30 23:12:36 2017 Successful ARP Flush on interface [14] {4E56AD95-0ECF-412C-9467-C01FDA916F99}
Sun Apr 30 23:12:36 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Sun Apr 30 23:12:37 2017 write UDP: No Route to Host (WSAEHOSTUNREACH) (code=10065)
Sun Apr 30 23:12:41 2017 Initialization Sequence Completed
Mon May 01 09:00:32 2017 [4e6f0e412dafba4add2d6178916260a5] Inactivity timeout (--ping-restart), restarting
Mon May 01 09:00:32 2017 SIGUSR1[soft,ping-restart] received, process restarting
Mon May 01 09:00:37 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.4:1198
Mon May 01 09:00:37 2017 UDP link local: (not bound)
Mon May 01 09:00:37 2017 UDP link remote: [AF_INET]172.98.67.4:1198
Mon May 01 09:01:37 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon May 01 09:01:37 2017 TLS Error: TLS handshake failed
Mon May 01 09:01:37 2017 SIGUSR1[soft,tls-error] received, process restarting
Mon May 01 09:01:42 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.4:1198
Mon May 01 09:01:42 2017 UDP link local: (not bound)
Mon May 01 09:01:42 2017 UDP link remote: [AF_INET]172.98.67.4:1198
Mon May 01 09:02:42 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon May 01 09:02:42 2017 TLS Error: TLS handshake failed
Mon May 01 09:02:42 2017 SIGUSR1[soft,tls-error] received, process restarting
Mon May 01 09:02:47 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.4:1198
Mon May 01 09:02:47 2017 UDP link local: (not bound)
Mon May 01 09:02:47 2017 UDP link remote: [AF_INET]172.98.67.4:1198
Mon May 01 09:03:47 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon May 01 09:03:47 2017 TLS Error: TLS handshake failed
Mon May 01 09:03:47 2017 SIGUSR1[soft,tls-error] received, process restarting
Mon May 01 09:03:52 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.4:1198
Mon May 01 09:03:52 2017 UDP link local: (not bound)
Mon May 01 09:03:52 2017 UDP link remote: [AF_INET]172.98.67.4:1198
Mon May 01 09:03:52 2017 [4e6f0e412dafba4add2d6178916260a5] Peer Connection Initiated with [AF_INET]172.98.67.4:1198
Mon May 01 09:03:58 2017 AUTH: Received control message: AUTH_FAILED
Mon May 01 09:03:58 2017 SIGUSR1[soft,auth-failure] received, process restarting
Mon May 01 15:01:35 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.67.4:1198
Mon May 01 15:01:35 2017 UDP link local: (not bound)
Mon May 01 15:01:35 2017 UDP link remote: [AF_INET]172.98.67.4:1198
Mon May 01 15:01:35 2017 [4e6f0e412dafba4add2d6178916260a5] Peer Connection Initiated with [AF_INET]172.98.67.4:1198
Mon May 01 15:01:36 2017 Preserving previous TUN/TAP instance: pia virtual
Mon May 01 15:01:36 2017 NOTE: Pulled options changed on restart, will need to close and reopen TUN/TAP device.
Mon May 01 15:01:38 2017 open_tun
Mon May 01 15:01:38 2017 TAP-WIN32 device [pia virtual] opened: \\.\Global\{4E56AD95-0ECF-412C-9467-C01FDA916F99}.tap
Mon May 01 15:01:38 2017 Notified TAP-Windows driver to set a DHCP IP/netmask of 10.56.10.6/255.255.255.252 on interface {4E56AD95-0ECF-412C-9467-C01FDA916F99} [DHCP-serv: 10.56.10.5, lease-time: 31536000]
Mon May 01 15:01:38 2017 Successful ARP Flush on interface [14] {4E56AD95-0ECF-412C-9467-C01FDA916F99}
Mon May 01 15:01:38 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Mon May 01 15:01:39 2017 write UDP: No Route to Host (WSAEHOSTUNREACH) (code=10065)
Mon May 01 15:01:43 2017 write UDP: No Route to Host (WSAEHOSTUNREACH) (code=10065)
Mon May 01 15:01:51 2017 Initialization Sequence Completed

**Comment by illumilore** [comment] 2017-05-02 03:56
The authenticate message at the beginning is repeated about 1000 times, but that is too much space.
The connection does work for at least a couple days usually before it disconnects and fails to reconnect, leaving the password blank, and I have never had any problems reconnecting after having to manually input the password again.

**Comment by selvanair** [comment] 2017-05-02 16:09
The logs show two occasions of ping-restart due to lost connectivity.  When it succeeds again after a few retries, the  server returns auth-failure which causes the saved password to be erased..  During ping-restart openvpn uses the password cached in memory (without consulting the GUI) and that seems to be failing for some reason. Logs with "verb 4" will show more info but without access to server logs it would be hard to say why auth fails.

Please test the following: when connected, do a reconnect using the "Reconnect" button on the status window. This should work without any password prompt even if password is not saved by the GUI. If it fails to reconnect with auth-failure and prompts for username/password, then the problem is in the password cached by openvpn core and should be reproducible even without using the GUI.

**Comment by illumilore** [comment] 2017-05-04 04:44
Hitting reconnect says "ReConnecting to <name of vpn server> has failed" and then hitting okay just makes the status window disappear.

**Comment by selvanair** [comment] 2017-05-04 14:24
Then the problem is not in the GUI as auth failed happens before password dialog. During reconnect the first attempt is made by openvpn using cached password and that fails (unless auth-nocache is in use which is not the case here). This issue better discussed in the openvpn mailing list or Trac. Please post  the log showing auth-fail during manual reconnect to openvpn-devel list or open a  Trac ticket (https://community.openvpn.net/openvpn/newticket)

**Comment by selvanair** [comment] 2017-05-12 14:51
Closing this as the discussion has moved to [Trac #885](https://community.openvpn.net/openvpn/ticket/885)

**Closed by selvanair** 2017-05-12 14:51 UTC
