### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by zero77** [OpenVPN/openvpn-gui#125] opened 2017-01-26 14:37 UTC
Can you add support for automatic updates, so you don't have to reinstall it every time there's a new update available.

**Comment by cron2** [comment] 2017-01-26 14:42
hi,

On Thu, Jan 26, 2017 at 06:37:07AM -0800, zero77 wrote:
> Can you add support for automatic updates, so you don't have to reinstall it every time there's a new update available.

Duplicate of https://community.openvpn.net/openvpn/ticket/769 

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by mattock** [comment] 2017-03-23 08:44
Closing as duplicate.

**Closed by mattock** 2017-03-23 08:44 UTC
